{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace }}
  labels: {{ include "newrelic.labels" . | indent 4 }}
  annotations:
{{ toYaml .Values.serviceAccount.annotations | indent 4}}
  name: {{ template "newrelic.serviceAccountName" . }}
{{- end -}}
